menu:
  Home: /
  Archives: /archives
  About: /2023/05/20/about/me/

# Google Analytics
google_analytics:
  enable: false
  acct_ga4: "G-12TTYHVW2Q"

# Word count (needs hexo-wordcount)
word_count: true

# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
  startOnload: true  #// default true